### ISSUE TITLE
[FEATURE] ChatGPT 음성 데이터 수신 

### ISSUE THREAD

**Issue by choiyoorim** [Nuri-Capstone/frontend#15]
## 🌴 작업 브랜치 
`feature/#15`

## 💼 TASK 개요 
- 음성 데이터 수신 후 자동으로 재생
- 음성 데이터 재생시에는 녹음 불가능하게 처리

## ✅ TODO 및 진행현황 

- [ ] 음성 데이터 수신시 사용할 라이브러리 선택
- [ ] 음성 데이터 수신 처리 로직 추가
- [ ] 음성 데이터 재생
