### ISSUE TITLE
[BUG] 홈 피드 오류 해결

### ISSUE THREAD

**Issue by senzoo-oh** [Nuri-Capstone/frontend#33]
## ✅ Bug Report check list

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [ ] Assignees, Label을 붙여주세요.

## BUG 개요

- 이런 버그가 있어
- 그래서 이런 문제가 있어
- 이런 식으로 재현이 돼
- 이 파일에서 문제가 발생한 거 같아

## TODO

- [ ] 이거 하려면 이런 걸 해야해
- [ ] 이것도 해야할 것 같아
